
name: Deploy to check cache

on: workflow_dispatch

env:
  AWS_REGION: 'ap-south-1'
  S3_BUCKET: 'meta-tags-test'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy To Production S3
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AK }}
          aws-secret-access-key: ${{ secrets.SAK }}
          aws-region: 'ap-south-1'

     
      - name: Sync files to S3
        run: |
          aws s3 sync test/ s3://$S3_BUCKET --include "*" --exclude "index.html" --cache-control "public, max-age=31536000, immutable" 
          aws s3 sync --delete test/ s3://$S3_BUCKET 
          aws s3 sync test/ s3://$S3_BUCKET --exclude "*" --include "index.html" --cache-control "no-cache, no-store, must-revalidate" \ --content-type "text/html"

